apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: runners
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: curlimages/curl
        name: curl
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
