---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx:1.5
    name: nginx
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 6335
    resources:
      requests:
        memory: 5Mi
        cpu: 5m
      limits:
        memory: 5Mi
        cpu: 5m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: runners
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - image: nginx:1.5
        name: nginx
        resources:
          requests:
            memory: 5Mi
            cpu: 5m
          limits:
            memory: 5Mi
            cpu: 5m
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 6335
